
services:

  django_test:
    build: .
    container_name: django_test
    volumes:
      - media:/app/media
      - static_file:/stat//staticfile


    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      echo 'Y' | python manage.py search_index --rebuild &&
      python manage.py collectstatic --noinput &&
      gunicorn auto_parts_store.wsgi
      "
    depends_on:
      postgres:
        condition: service_healthy
      elastic:
        condition: service_healthy
      redis_django:
        condition: service_healthy
    networks:
      - test
  elastic:
    container_name: elastic_test
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cat/health?h=status | grep -q green" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    networks:
      - test

  postgres:
    container_name: postgres_test
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_PASSWORD="1234"
      - POSTGRES_DB="auto"
    networks:
      - test
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5


  redis_django:

    image: redis

    container_name: redist-test
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s

    volumes:
      - redis-data:/data

    networks:
      - test
  celery:
    image:  2-django_test
    container_name: celery_test

    command: >
      sh -c "
      celery -A auto_parts_store worker -l info
      "
    networks:
      - test
  celery_beat:
    image: 2-django_test
    container_name: celery_beat_test
    command: >
      sh -c "
      celery -A auto_parts_store beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
    networks:
      - test
    depends_on:
      postgres:
        condition: service_healthy
      django_test:
        condition: service_started
      celery:
        condition: service_started
      elastic:
        condition: service_healthy

  nginx:
    image: nginx
    depends_on:
      - django_test

    container_name: nginx_test

    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_file:/stat//staticfile
    networks:
      - test




networks:
  test:
    driver: bridge

volumes:
  redis-data:
    name: redis


  db-data:
    name: data

  elasticsearch-data:
    name: elastic

  media:
    name: media

  static_file:
